# Generated by Django 5.0.2 on 2024-02-10 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toolapp", "0002_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("image", models.ImageField(blank=True, null=True, upload_to="blogs/")),
            ],
        ),
        migrations.CreateModel(
            name="ContentCreator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("website", models.URLField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="contentcreators/"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FAQ",
        ),
        migrations.DeleteModel(
            name="person",
        ),
        migrations.AddField(
            model_name="blog",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to="toolapp.contentcreator",
            ),
        ),
    ]
