# Generated by Django 5.0.2 on 2024-02-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toolapp", "0003_blog_contentcreator_delete_faq_delete_person_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(max_length=1000)),
            ],
        ),
    ]
