# Generated by Django 5.0.2 on 2024-02-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toolapp", "0006_user_register"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_register",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user_register",
            name="age",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user_register",
            name="contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user_register",
            name="dob",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user_register",
            name="pincode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
