# Generated by Django 5.0.2 on 2024-02-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toolapp", "0008_user_register_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="helpus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=100)),
                ("content", models.TextField(max_length=1000)),
            ],
        ),
    ]
