# Generated by Django 5.0.2 on 2024-02-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toolapp", "0009_helpus"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_register",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="data"),
        ),
    ]
